# Generated by Django 5.1 on 2026-05-04 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('seed_color', models.CharField(default='#1976D2', max_length=7)),
                ('theme_mode', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='system', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
            },
        ),
    ]
